#:schema https://schemas.spinframework.dev/spin/manifest-v2/latest.json

spin_manifest_version = 2

[application]
name = "url-shortener"
version = "0.1.0"
authors = ["Caleb Schoepp <caleb.schoepp@fermyon.com>"]
description = "Shorten URLs"

[[trigger.http]]
route = "/..."
component = "url-shortener"

[component.url-shortener]
source = "target/wasm32-wasip1/release/url_shortener.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]
[component.url-shortener.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
